### ISSUE TITLE
Incorrectly parses css mime types

### ISSUE THREAD

**Issue by JustinBeaudry** [ahupp/python-magic#107]
Given the 3 following test cases:

test1.css:
``` css
.header {
  text-align: center;
}
```
test2.css
``` css
@media(min-size: 760px) {
  text-align: left;
}

.header {
  text-align: center;
}
```
test3.css
``` css
.header {
  text-align: center;
}

.text {
  font-family: 'Proxima Nova', sans-serif;
}
```
and running the following python script:
``` python
import magic
magic.from_file("test1.css", mime=True)
magic.from_file("test2.css", mime=True)
magic.from_file("test3.css", mime=True)
```
outputs 
```
'text/plain'
'text-plain'
'text/x-asm'
```

All three of these files are very basic examples of a valid css file.
